### ISSUE TITLE
个人资料模块布局有问题

### ISSUE THREAD

**Issue by kxxoling** [numbbbbb/githuber.info#17]
如[链接](http://githuber.info/search/kxxoling?token=6b391cf42b8f3a3ad59248c97b807829a14c20ba)，虽然声明了 col-row-10 ，但是又定义了

``` css
.col-md-4 {
  width: 33.33333333%;
}
```

导致布局失败，邮箱错乱到下一行了。

去掉就好了：

![2015-03-25 5 30 56](https://cloud.githubusercontent.com/assets/1227139/6821743/e5f150c8-d314-11e4-8997-1dc7e71ee9ee.png)
